source "https://rubygems.org"

gem "middleman"            , "~>3.0.7"
gem "middleman-livereload" , "~> 3.0.1"
gem "httparty"             , "~> 0.10.2"
gem "nokogiri"             , "~> 1.6.0"
gem "hashugar"             , "~> 0.0.6"